"""
Email dispatch service via SMTP.
Gracefully degrades to a simulated send if SMTP credentials are not configured.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_email(to_email: str, subject: str, body_text: str, sender_name: str = "CivicPulse") -> bool:
    smtp_host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_pass = os.environ.get("SMTP_PASS", "")

    if not smtp_user or not smtp_pass:
        print(f"[Email] SMTP not configured — simulating send to: {to_email}")
        print(f"[Email] Subject: {subject}")
        return True

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{sender_name} <{smtp_user}>"
        msg["To"] = to_email

        msg.attach(MIMEText(body_text, "plain"))
        msg.attach(MIMEText(
            f"""<html>
<body style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px">
  <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:8px;padding:32px;border:1px solid #e5e7eb">
    <div style="display:flex;align-items:center;margin-bottom:24px">
      <div style="background:#10b981;width:32px;height:32px;border-radius:6px;display:inline-flex;align-items:center;justify-content:center;color:#000;font-weight:bold;margin-right:12px">CP</div>
      <span style="font-size:18px;font-weight:600;color:#111">CivicPulse</span>
    </div>
    <pre style="white-space:pre-wrap;font-family:Arial,sans-serif;font-size:14px;line-height:1.7;color:#374151">{body_text}</pre>
    <hr style="margin:24px 0;border-color:#f3f4f6">
    <p style="color:#9ca3af;font-size:12px;margin:0">
      This letter was automatically generated by CivicPulse — a citizen-powered civic intelligence platform.<br>
      Powered by Google Gemini AI.
    </p>
  </div>
</body>
</html>""",
            "html",
        ))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [to_email], msg.as_string())

        print(f"[Email] Sent to {to_email}: {subject}")
        return True

    except Exception as e:
        print(f"[Email] Failed: {e}")
        return False

def send_escalation_email(to_email: str, authority_name: str, letter: str, issue_title: str) -> bool:
    subject = f"Civic Grievance — {issue_title} | CivicPulse"
    return send_email(to_email, subject, letter, sender_name="CivicPulse Grievance System")
