import google.generativeai as genai
import os
import json

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

flash_model = genai.GenerativeModel("gemini-1.5-flash")
pro_model = genai.GenerativeModel("gemini-1.5-pro")

ISSUE_CATEGORIES = [
    "POTHOLE", "STREETLIGHT", "WATER_LEAKAGE", "GARBAGE",
    "BROKEN_FOOTPATH", "DRAINAGE", "TREE_FALLEN", "ROAD_DAMAGE", "OTHER",
]

def _parse_json(text: str):
    text = text.strip()
    if text.startswith("```"):
        parts = text.split("```")
        text = parts[1] if len(parts) > 1 else text
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())

def classify_and_extract_issues(texts: list, location_hint: str = "") -> list:
    batch_text = "\n---\n".join([f"[{i+1}] {t}" for i, t in enumerate(texts)])
    prompt = f"""You are a civic issue detection AI for Indian cities.

Analyze these social media posts and identify real civic infrastructure complaints.
Location context: {location_hint}

Posts:
{batch_text}

For each REAL civic complaint (not opinions, not politics, not personal), extract:
- source_index: which post number (1-based)
- category: one of {ISSUE_CATEGORIES}
- title: short issue title (max 10 words)
- description: 1-2 sentence summary
- severity: LOW / MEDIUM / HIGH
- location_hint: any specific location mentioned

Return ONLY a valid JSON array. If no civic issues found, return [].
Example:
[{{"source_index": 1, "category": "POTHOLE", "title": "Large pothole on MG Road", "description": "Deep pothole near metro station.", "severity": "HIGH", "location_hint": "MG Road near metro"}}]
"""
    try:
        response = flash_model.generate_content(prompt)
        return _parse_json(response.text)
    except Exception as e:
        print(f"[Gemini] classify error: {e}")
        return []

def validate_photo_for_issue(photo_base64: str, issue_category: str, issue_title: str) -> dict:
    prompt = f"""You are a civic issue photo validator.

The citizen claims this photo shows: "{issue_title}" (category: {issue_category})

Analyze the image and determine:
1. Does this photo show a real civic infrastructure problem?
2. Does it match the stated category ({issue_category})?
3. Is this clearly an outdoor/public space photo (not a stock image)?

Return ONLY valid JSON:
{{"valid": true/false, "confidence": 0-100, "reasoning": "one sentence", "detected_issue": "what you actually see"}}
"""
    try:
        image_part = {"mime_type": "image/jpeg", "data": photo_base64}
        response = flash_model.generate_content([prompt, image_part])
        return _parse_json(response.text)
    except Exception as e:
        print(f"[Gemini] vision error: {e}")
        return {"valid": True, "confidence": 50, "reasoning": "Validation unavailable", "detected_issue": "Unknown"}

def identify_authority(issue: dict) -> dict:
    prompt = f"""You are an expert on Indian municipal governance.

Issue details:
- Category: {issue.get('category')}
- Title: {issue.get('title')}
- Location: {issue.get('location_name', 'Unknown')}
- Description: {issue.get('description')}

Identify the most appropriate government authority to escalate this to.
Consider: municipal corporation, PWD, water board, electricity board, NHAI, etc.

Return ONLY valid JSON:
{{
  "authority_name": "Full official name",
  "authority_type": "municipal/state/central",
  "department": "specific department name",
  "email": "grievance@[authority].gov.in format",
  "reasoning": "why this authority is responsible"
}}
"""
    try:
        response = flash_model.generate_content(prompt)
        return _parse_json(response.text)
    except Exception as e:
        print(f"[Gemini] authority error: {e}")
        return {
            "authority_name": "Municipal Corporation",
            "authority_type": "municipal",
            "department": "Public Works Department",
            "email": "grievance@municipality.gov.in",
            "reasoning": "Default escalation path",
        }

def draft_escalation_letter(issue: dict, authority: dict, confirmation_count: int) -> str:
    prompt = f"""Draft a formal civic grievance letter from CivicPulse (a citizen AI platform) to {authority['authority_name']}.

Issue details:
- Title: {issue['title']}
- Category: {issue['category']}
- Description: {issue['description']}
- Location: {issue.get('location_name', 'GPS: ' + str(issue['latitude']) + ', ' + str(issue['longitude']))}
- GPS Coordinates: {issue['latitude']}, {issue['longitude']}
- Citizens who confirmed this issue: {confirmation_count}
- First reported: {issue['created_at']}

Requirements:
- Professional, firm but respectful tone
- Reference the number of affected citizens
- Request specific action within 7 days for HIGH severity issues
- Include GPS coordinates for field teams
- End with: "This letter was auto-generated by CivicPulse, a citizen-powered civic intelligence platform."
- Keep under 300 words

Return the letter text only, no JSON.
"""
    try:
        response = pro_model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"[Gemini] letter error: {e}")
        return (
            f"Dear {authority['authority_name']},\n\n"
            f"We are writing to report: {issue['title']} at "
            f"{issue.get('location_name', 'GPS: ' + str(issue['latitude']) + ', ' + str(issue['longitude']))}. "
            f"This has been confirmed by {confirmation_count} citizens. Please take immediate action.\n\n"
            f"This letter was auto-generated by CivicPulse, a citizen-powered civic intelligence platform."
        )
