"""
Pre-defined demo issues for first-run seeding.
No Gemini API calls needed — instant startup, rate-limit safe.
Shows all 4 pipeline stages across 3 Indian cities.
"""
from database import seed_issue, get_all_issues

DEMO_ISSUES = [
    # ─── BENGALURU ─────────────────────────────────────────────────────────────

    {
        "title": "Large pothole on Indiranagar 100ft Road",
        "category": "POTHOLE",
        "description": "Deep pothole approximately 2 feet wide near Indiranagar metro station causing accidents. Multiple bike riders affected weekly.",
        "latitude": 12.9784, "longitude": 77.6408,
        "location_name": "100ft Road near Metro, Indiranagar, Bengaluru",
        "source_signals": [
            "The pothole on Indiranagar 100ft road is back!! Almost fell off my bike. @BBMP please fix #Bengaluru",
            "Another day, another pothole on Indiranagar road. Count: 3 complaints this week. Nothing happens.",
            "Same pothole on Indiranagar 100ft road got me again! When will @BBMP fix this? Third complaint",
        ],
        "confidence_score": 85,
        "confirmation_count": 7,
        "status": "ESCALATED",
        "authority_name": "Bruhat Bengaluru Mahanagara Palike",
        "authority_email": "commissioner@bbmp.gov.in",
        "escalation_sent_at": "2026-06-22 09:15:00",
        "escalation_letter": """Dear Commissioner, Bruhat Bengaluru Mahanagara Palike,

Subject: Urgent Civic Grievance — Large Pothole, Indiranagar 100ft Road, Bengaluru

We are writing on behalf of CivicPulse, a citizen-powered civic intelligence platform, to formally escalate a serious road safety hazard confirmed by 7 independent residents of Bengaluru.

A large, dangerous pothole (approximately 2 feet wide, 8 inches deep) has been identified on 100ft Road near Indiranagar Metro Station. GPS Coordinates: 12.9784°N, 77.6408°E.

This issue was first detected by our AI Discovery Agent scanning public social media signals, and has since been independently confirmed by 7 citizens through on-ground verification. The pothole is responsible for multiple vehicular accidents and poses an ongoing daily risk to commuters.

We respectfully request the Roads & Infrastructure Division of BBMP to:
1. Deploy a repair crew to the above GPS coordinates within 7 days
2. Install temporary safety barriers until permanent repair is completed
3. Send confirmation of action to this grievance

This level of documented civic hazard — confirmed by 7 citizens with photographic evidence — warrants urgent attention under BBMP's mandate for road maintenance and public safety.

Yours sincerely,
CivicPulse Grievance System
On behalf of 7 confirmed citizens, Bengaluru

This letter was auto-generated by CivicPulse, a citizen-powered civic intelligence platform.""",
    },
    {
        "title": "Streetlight outage Koramangala 5th Block junction",
        "category": "STREETLIGHT",
        "description": "Three consecutive streetlights non-functional for 5 days near 5th block main junction. Dangerously dark after sunset, raising safety concerns.",
        "latitude": 12.9352, "longitude": 77.6245,
        "location_name": "5th Block Junction, Koramangala, Bengaluru",
        "source_signals": [
            "Streetlight near Koramangala 5th block not working since 3 days. Very dark and unsafe at night #BBMP",
            "Broken streetlight near Koramangala junction — nearly had an accident last night. No lighting at all!",
        ],
        "confidence_score": 65,
        "confirmation_count": 5,
        "status": "CONFIRMED",
    },
    {
        "title": "Garbage overflow BTM Layout Sector 7",
        "category": "GARBAGE",
        "description": "Municipal garbage not collected for 4 days. Bins overflowing onto footpath creating a health hazard and severe foul smell in the area.",
        "latitude": 12.9166, "longitude": 77.6101,
        "location_name": "Sector 7 Main Road, BTM Layout, Bengaluru",
        "source_signals": [
            "Garbage not collected in BTM layout for 4 days. Stinking badly. Where is BBMP? #SwachhBharat",
        ],
        "confidence_score": 25,
        "confirmation_count": 1,
        "status": "DISCOVERED",
    },
    {
        "title": "Water pipe burst on 80ft Road Koramangala",
        "category": "WATER_LEAKAGE",
        "description": "Underground BWSSB water pipe burst causing road flooding. Significant water wastage and traffic disruption for several hours.",
        "latitude": 12.9279, "longitude": 77.6271,
        "location_name": "80ft Road, Koramangala, Bengaluru",
        "source_signals": [
            "Water board pipe burst on 80ft road Koramangala. Road flooded and traffic jammed for hours today",
        ],
        "confidence_score": 30,
        "confirmation_count": 2,
        "status": "DISCOVERED",
    },

    # ─── MUMBAI ────────────────────────────────────────────────────────────────

    {
        "title": "Waterlogging blocks Andheri-Kurla Link Road",
        "category": "DRAINAGE",
        "description": "Severe waterlogging due to blocked storm drains on Andheri-Kurla Link Road. Third occurrence this month. Traffic at complete standstill.",
        "latitude": 19.1136, "longitude": 72.8697,
        "location_name": "Andheri-Kurla Link Road, Andheri East, Mumbai",
        "source_signals": [
            "@BMC Mumbai waterlogging on Andheri Link road again. 3rd time this month. Nothing is being fixed.",
            "Flooded road near Andheri again! Drains blocked, water knee-deep. @BMC_Mumbai please respond!",
        ],
        "confidence_score": 60,
        "confirmation_count": 5,
        "status": "CONFIRMED",
    },
    {
        "title": "Pothole craters near Bandra station west",
        "category": "POTHOLE",
        "description": "Multiple deep potholes forming craters on Station Road leading to Bandra railway station west entrance. High pedestrian and vehicle traffic area.",
        "latitude": 19.0596, "longitude": 72.8397,
        "location_name": "Station Road West, Bandra, Mumbai",
        "source_signals": [
            "Station road Bandra west is a disaster zone — craters everywhere. @BMC when will this be fixed??",
        ],
        "confidence_score": 20,
        "confirmation_count": 1,
        "status": "DISCOVERED",
    },

    # ─── HYDERABAD ─────────────────────────────────────────────────────────────

    {
        "title": "Pothole cluster near Gachibowli circle",
        "category": "POTHOLE",
        "description": "Multiple potholes in a 100m stretch near Gachibowli circle on the HITEC City road. Causing daily accidents and tyre damage on a high-traffic tech corridor.",
        "latitude": 17.4401, "longitude": 78.3489,
        "location_name": "Gachibowli Circle, HITEC City, Hyderabad",
        "source_signals": [
            "GHMC fix the broken road near Gachibowli circle please! Pothole took out my tyre this morning",
        ],
        "confidence_score": 25,
        "confirmation_count": 2,
        "status": "DISCOVERED",
    },
    {
        "title": "Broken footpath near Hitech City metro exit",
        "category": "BROKEN_FOOTPATH",
        "description": "Footpath tiles completely broken and displaced near Hitech City metro station exit gate 2. Dangerous for pedestrians, especially senior citizens during rush hour.",
        "latitude": 17.4478, "longitude": 78.3762,
        "location_name": "Metro Exit Gate 2, Hitech City, Hyderabad",
        "source_signals": [
            "The footpath near Hitech City metro is completely broken. Senior citizens struggling to walk. GHMC please fix!",
        ],
        "confidence_score": 20,
        "confirmation_count": 1,
        "status": "DISCOVERED",
    },
]


def seed_database() -> int:
    """Seed the database with demo issues. Returns number of issues inserted."""
    count = 0
    for issue in DEMO_ISSUES:
        seed_issue(issue)
        count += 1
    print(f"[Seed] Inserted {count} demo issues across Bengaluru, Mumbai, Hyderabad")
    return count
